name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgree
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: nome_database
        ports:
          - 5432:5432

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Esperar o PostgreSQL ficar pronto
        run: sleep 15

      - name: Testar conexão com PostgreSQL
        run: |
          for i in {1..5}; do
            pg_isready -h postgree -p 5432 -U postgres && break
            echo "Aguardando PostgreSQL..."
            sleep 5
          done


      - name: Executar pytest
        env:
          DATABASE_URL: postgresql://postgres:12345@postgree:5432/nome_database
        run: pytest teste.py
